#!/usr/bin/with-contenv bash

variables='${HOSTNAME}'
envsubst "${variables}" < policyd-spf.conf.tmpl > /etc/postfix-policyd-spf-python/policyd-spf.conf

touch /data/virtual
postmap /data/virtual

postfix check 2>&1 || exit ${?}
exec /usr/lib/postfix/master -d
